name: term-proj-g9
services:
  postgres:
    image: postgres:18-alpine
    container_name: term-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - term-data:/var/lib/postgresql
      - ./_entrypoint:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    networks:
      - term-net
volumes:
  term-data:
networks:
  term-net: